### ISSUE TITLE
[BUG] InviteTracker wont load.

### ISSUE THREAD

**Issue by yuv41** [OofChair/OofCogs#27]
What cog is the bug on?
InviteTracker
**Describe the bug**
Cog wont load.
File "/root/redbot/data/newvision/cogs/CogManager/cogs/invitetracker/invitetracker.py", line 33, in __init__
bot.loop.create_task(self.load(ctx))
NameError: name 'ctx' is not defined

**To Reproduce**
Load cog.

**Expected behavior**
To load 
**Additional context**
pls fix <3

**Comment by OofChair** [comment]
Hi, 
Thank you for reporting the bug but next time please either report it on my Discord server or my GitHub repo, not both 🙂

**Comment by yuv41** [comment]
> Hi, 
> 
> Thank you for reporting the bug but next time please either report it on my Discord server or my GitHub repo, not both 🙂

I only reported on github but ok(?)
